pipeline {
    agent any

    stages {
        stage('Git Version') {
            steps {
                sh 'git version'
            }
        }
        
        stage('Maven Version') {
            steps {
                echo 'mvn -v'
            }
        }
        
        stage('Docker Version') {
            steps {
                sh 'docker -v '
            }
        }
        
        stage('K8S Version') {
            steps {
                withKubeConfig([credentialsId: 'kubeconfig']) {
                sh 'kubectl version --short'
                }
            }
        }
        
    }
}
